# Header [ menu > group > item ]
menu:
  default:
    派對活動:
      url: /
      icon: local_activity
    舞蹈聯誼簡介:
      url: /舞蹈聯誼
      icon: info
  聯絡我們: 
    Facebook:
      url: https://facebook.com/welovewedance
      external: true
      img: /imgs/facebook-logo.png
    Messenger:
      url: https://m.me/welovewedance
      external: true
      img: https://upload.wikimedia.org/wikipedia/commons/3/3b/Facebook_Messenger_logo.svg
    LINE:
      url: https://line.me/R/ti/p/%40425yeuur
      external: true
      img: https://upload.wikimedia.org/wikipedia/commons/4/41/LINE_logo.svg

node_sass:
  includePaths:
    - "./node_modules"
  outputStyle: nested
  precision: 5
  sourceComments: false

google_analytics: UA-137015305-1
facebook_pixel: 884433178557539